version: '3.8'

services:
  moodify-app:
    build:
      context: .
      args:
        NEXT_PUBLIC_API_KEY: ${NEXT_PUBLIC_API_KEY}
        NEXT_PUBLIC_AUTH_DOMAIN: ${NEXT_PUBLIC_AUTH_DOMAIN}
        NEXT_PUBLIC_PROJECT_ID: ${NEXT_PUBLIC_PROJECT_ID}
        NEXT_PUBLIC_STORAGE_BUCKET: ${NEXT_PUBLIC_STORAGE_BUCKET}
        NEXT_PUBLIC_MESSAGING_SENDER_ID: ${NEXT_PUBLIC_MESSAGING_SENDER_ID}
        NEXT_PUBLIC_APP_ID: ${NEXT_PUBLIC_APP_ID}
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_KEY=${NEXT_PUBLIC_API_KEY}
      - NEXT_PUBLIC_AUTH_DOMAIN=${NEXT_PUBLIC_AUTH_DOMAIN}
      - NEXT_PUBLIC_PROJECT_ID=${NEXT_PUBLIC_PROJECT_ID}
      - NEXT_PUBLIC_STORAGE_BUCKET=${NEXT_PUBLIC_STORAGE_BUCKET}
      - NEXT_PUBLIC_MESSAGING_SENDER_ID=${NEXT_PUBLIC_MESSAGING_SENDER_ID}
      - NEXT_PUBLIC_APP_ID=${NEXT_PUBLIC_APP_ID}
    networks:
      - moodify-network

networks:
  moodify-network:
    driver: bridge
